sudo: false  # use container-based infrastructure
language: python
python:
  - "2.7"
install: "pip install -r requirements.txt"
script: nosetests --with-coverage --cover-tests

after_success:
  coveralls
